#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include "feature.h"
#include "cluster.h"
#include "dtw_sync.h"
#include "dtw_gaussian.h"


int main(int argc, char **argv)
{
    if(argc < 3)
    {
        printf("Usage: bin/gaussiandtw [threshold] [path/to/test.out]\n");
        printf("    Takes in the pruning threshold (0 for no pruning),\n");
        printf("    the test output file generated by bin/cepstrum\n\n");
        printf("    Uses a guassian HMM to compare against each template.\n\n");
        exit(1);
    }

    
    //Read in pruning types
    double threshold = strtod(argv[1],NULL);
    dtw_prune_t prune;
    if(threshold == 0.0)
        prune = DTW_NO_PRUNE;
    else
        prune = DTW_BEAM_PRUNE;


    // Read in test file
    feature_vectors* test = features_from_file(argv[2]);


    // Read in each template set to cluster... Hardcoded, sorry
    gaussian_cluster* zero_template = read_cluster_from_file("zero");
    gaussian_cluster* one_template = read_cluster_from_file("one");
    gaussian_cluster* two_template = read_cluster_from_file("two");
    gaussian_cluster* three_template = read_cluster_from_file("three");
    gaussian_cluster* four_template = read_cluster_from_file("four");
    gaussian_cluster* five_template = read_cluster_from_file("five");
    gaussian_cluster* six_template = read_cluster_from_file("six");
    gaussian_cluster* seven_template = read_cluster_from_file("seven");
    gaussian_cluster* eight_template = read_cluster_from_file("eight");
    gaussian_cluster* nine_template = read_cluster_from_file("nine");


    //Package these for using
    int num_templates = 10;
    gaussian_cluster** templates = malloc(10*sizeof(gaussian_cluster));
    templates[0] = zero_template;
    templates[1] = one_template;
    templates[2] = two_template;
    templates[3] = three_template;
    templates[4] = four_template;
    templates[5] = five_template;
    templates[6] = six_template;
    templates[7] = seven_template;
    templates[8] = eight_template;
    templates[9] = nine_template;

    //Create our trellis structures
    dtw_t** dtws = get_gaussian_trellis(test, templates, num_templates, prune, threshold);

    printf("Comparing %s against %d templates with threshold %1.4lf\n\n",
           argv[2],num_templates,threshold);

    //Get n best
    dtw_t** results = get_best_n_from_trellis(dtws, num_templates, 5, threshold);

    //Print results
    print_gaussian_results(results, 5);

    return 0;
}

