#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include "feature.h"
#include "cluster.h"
#include "dtw_sync.h"
#include "dtw_gaussian.h"


int main(int argc, char **argv)
{
    if(argc < 3)
    {
        printf("Usage: bin/gaussiandtw [threshold] [path/to/test.out]\n");
        printf("    Takes in the pruning threshold (0 for no pruning),\n");
        printf("    the test output file generated by bin/cepstrum\n\n");
        printf("    Uses a guassian HMM to compare against each template.\n\n");
        exit(1);
    }

    
    //Read in pruning types
    double threshold = strtod(argv[1],NULL);
    dtw_prune_t prune;
    if(threshold == 0.0)
        prune = DTW_NO_PRUNE;
    else
        prune = DTW_BEAM_PRUNE;


    // Read in test file
    feature_vectors* test = features_from_file(argv[2]);


    // Read in each template set to cluster... Hardcoded, sorry
    char* ones[5] = {"analysis/one1-40.out","analysis/one2-40.out",
                     "analysis/one3-40.out","analysis/one4-40.out",
                     "analysis/one4-40.out"};
    feature_vectors** one_features = features_from_all_files(ones,5);
    gaussian_cluster* one_template = cluster_templates(one_features,5,"one");

    char* twos[5] = {"analysis/two1-40.out","analysis/two2-40.out",
                     "analysis/two3-40.out","analysis/two4-40.out",
                     "analysis/two4-40.out"};
    feature_vectors** two_features = features_from_all_files(twos,5);
    gaussian_cluster* two_template = cluster_templates(two_features,5,"two");

    char* threes[5] = {"analysis/three1-40.out","analysis/three2-40.out",
                     "analysis/three3-40.out","analysis/three4-40.out",
                     "analysis/three4-40.out"};
    feature_vectors** three_features = features_from_all_files(threes,5);
    gaussian_cluster* three_template = cluster_templates(three_features,5,"three");

    char* fours[5] = {"analysis/four1-40.out","analysis/four2-40.out",
                     "analysis/four3-40.out","analysis/four4-40.out",
                     "analysis/four4-40.out"};
    feature_vectors** four_features = features_from_all_files(fours,5);
    gaussian_cluster* four_template = cluster_templates(four_features,5,"four");

    char* fives[5] = {"analysis/five1-40.out","analysis/five2-40.out",
                     "analysis/five3-40.out","analysis/five4-40.out",
                     "analysis/five4-40.out"};
    feature_vectors** five_features = features_from_all_files(fives,5);
    gaussian_cluster* five_template = cluster_templates(five_features,5,"five");

    //Package these for using
    gaussian_cluster** templates = malloc(5*sizeof(gaussian_cluster));
    templates[0] = one_template;
    templates[1] = two_template;
    templates[2] = three_template;
    templates[3] = four_template;
    templates[4] = five_template;


    //Create our trellis structures
    dtw_t** dtws = get_gaussian_trellis(test, templates, 5, prune, threshold);

    // Now use gaussian parameters to calculate probabilities
    //single_gaussian_params** gaussian_params = cluster_templates(templates,num_templates);
    //gaussian_params = gaussian_params;
    //for(int i =0; i<NUM_CLUSTERS; i++){
        //print_single_gaussian_params(gaussian_params[i]);
    //}		


    printf("Comparing %s against 5 templates with threshold %1.4lf\n\n",
           argv[2],threshold);

    //Get n best
    dtw_t** results = get_best_n_from_trellis(dtws, 5, 5);

    //Print results
    print_gaussian_results(results, 5);

    return 0;
}

